### ISSUE TITLE
Nie ma sensu dodawać wszystkich możliwych liczb

### ISSUE THREAD

**Issue by ghost** [MateuszG92/ALXkurs#2]
https://github.com/MateuszG92/ALXkurs/blob/66a1ba67ac00fc1d0b18242935b0e75571fe44dc/LottoFormapp/Form1.cs#L37

Random działa tak, że można generować liczby w granicach
rnd.NextInt(2,5); na przykład wygeneruje inta między 2 a 5

https://learn.microsoft.com/en-us/dotnet/api/system.random?view=net-7.0
https://stackoverflow.com/questions/2706500/how-do-i-generate-a-random-integer-in-c

**Comment by CrimsonR4ven** [comment]
Witam, w pełni się z Panem zgadzam jednak zauważyłem już dwa tygodnie temu że NextInt to po prostu Next

**Comment by MateuszG92** [comment]
Panem? OoO
